// Facts about the U.S. Constitution — each card gets a category tag + fact text.
const FACTS = [
  { tag: "Origins", text: "The Constitution was signed on September 17, 1787, in Philadelphia — the day is now celebrated as Constitution Day." },
  { tag: "Origins", text: "Only 39 of the 55 delegates at the Constitutional Convention actually signed the final document." },
  { tag: "Structure", text: "The Constitution has just 7 Articles and, today, 27 Amendments — remarkably short compared to most national constitutions." },
  { tag: "Structure", text: "At about 4,400 words in its original form, the U.S. Constitution is the shortest written constitution of any major world government." },
  { tag: "Preamble", text: "The Preamble's famous opening, \"We the People,\" was written by Gouverneur Morris, who is credited with much of the document's final wording." },
  { tag: "Ratification", text: "The Constitution didn't take effect until 9 of the 13 states ratified it — that threshold was hit on June 21, 1788, with New Hampshire's vote." },
  { tag: "Ratification", text: "Rhode Island was the last of the original 13 states to ratify — it didn't sign on until May 1790, over a year after Washington's inauguration." },
  { tag: "Bill of Rights", text: "The Bill of Rights wasn't part of the original Constitution — it was added as the first 10 Amendments in 1791 to satisfy Anti-Federalist concerns." },
  { tag: "Bill of Rights", text: "James Madison originally proposed 19 amendments; Congress narrowed the list to 12, and the states ratified 10 of those as the Bill of Rights." },
  { tag: "Bill of Rights", text: "One of Madison's original proposed amendments about congressional pay wasn't ratified until 1992 — 203 years later — becoming the 27th Amendment." },
  { tag: "First Amendment", text: "The First Amendment protects five distinct freedoms: religion, speech, press, assembly, and petitioning the government." },
  { tag: "Amendments", text: "The 13th Amendment (1865) abolished slavery, the 14th (1868) guaranteed equal protection, and the 15th (1870) barred voting discrimination by race." },
  { tag: "Amendments", text: "The 18th Amendment established Prohibition in 1919, and the 21st Amendment repealed it in 1933 — the only amendment ever undone by another." },
  { tag: "Amendments", text: "The 19th Amendment, ratified in 1920, guaranteed women the right to vote after decades of suffragist activism." },
  { tag: "Amendments", text: "The 22nd Amendment (1951) limits presidents to two elected terms, a response to Franklin D. Roosevelt's four-term presidency." },
  { tag: "Amendments", text: "The 26th Amendment lowered the voting age to 18 in 1971, driven partly by the argument that soldiers old enough to be drafted should be old enough to vote." },
  { tag: "Branches", text: "Article I establishes the Legislative Branch first — a signal that the framers saw Congress as the branch closest to the people." },
  { tag: "Branches", text: "Article II creates the Presidency but never uses the words \"cabinet\" or \"executive branch officers\" by that name — the Cabinet evolved by practice, not text." },
  { tag: "Branches", text: "Article III is the shortest of the three branch articles and left it to Congress to decide how many federal courts would even exist below the Supreme Court." },
  { tag: "Checks & Balances", text: "The President can veto legislation, but Congress can override that veto with a two-thirds majority in both the House and Senate." },
  { tag: "Checks & Balances", text: "The Supreme Court's power of judicial review — striking down unconstitutional laws — isn't explicitly written in the Constitution; it was established by Marbury v. Madison in 1803." },
  { tag: "Electoral College", text: "The Electoral College, created in Article II, means voters technically elect \"electors,\" not the President directly." },
  { tag: "Electoral College", text: "A candidate can win the presidency while losing the nationwide popular vote — it has happened five times, most recently in 2016." },
  { tag: "Congress", text: "The Constitution requires a census every 10 years specifically to reapportion seats in the House of Representatives based on population." },
  { tag: "Congress", text: "Each state gets exactly two Senators regardless of population — a compromise designed to protect smaller states' influence." },
  { tag: "Amending Process", text: "Amending the Constitution requires two-thirds approval in both chambers of Congress, then ratification by three-fourths of the states — 38 of 50 today." },
  { tag: "Amending Process", text: "Article V also allows states themselves to call a constitutional convention to propose amendments, though this method has never been used successfully." },
  { tag: "Supremacy Clause", text: "The Supremacy Clause in Article VI makes the Constitution, federal laws, and treaties \"the supreme Law of the Land,\" overriding conflicting state laws." },
  { tag: "Oddities", text: "The Constitution never mentions the words \"democracy,\" \"God,\" or \"corporation\" anywhere in its text." },
  { tag: "Oddities", text: "It also never explicitly mentions political parties — the framers hoped factions could be avoided entirely." },
  { tag: "Oddities", text: "There is no constitutional requirement that Supreme Court Justices be lawyers, though every justice in history has held a law degree." },
  { tag: "Oddities", text: "The Constitution sets no term limit for federal judges — Article III grants them lifetime tenure \"during good Behaviour.\"" },
  { tag: "Amendments", text: "The 25th Amendment, ratified in 1967, spells out presidential succession and what happens if a president becomes unable to serve." },
  { tag: "Rights", text: "The right to a jury trial appears twice in the Constitution — once in Article III and again in the Sixth and Seventh Amendments." },
  { tag: "Rights", text: "The Fourth Amendment's protection against \"unreasonable searches and seizures\" grew directly out of colonial anger over British \"writs of assistance.\"" },
  { tag: "Slavery Compromise", text: "The original Constitution's Three-Fifths Compromise counted enslaved people as three-fifths of a person for representation and taxation purposes — later nullified by the 14th Amendment." },
  { tag: "Framers", text: "James Madison is often called the \"Father of the Constitution\" for his central role drafting it, though he insisted it was the work of many minds." },
  { tag: "Framers", text: "Benjamin Franklin, then 81 years old, was the oldest delegate at the Constitutional Convention and had to be carried to sessions in a sedan chair." },
  { tag: "Preservation", text: "The original signed Constitution is stored in the National Archives in Washington, D.C., inside a bulletproof, humidity-controlled titanium case." },
  { tag: "Preservation", text: "Each night, the displayed Constitution is lowered into a 55-ton vault designed to survive a nuclear attack." },
  { tag: "Global Influence", text: "The U.S. Constitution has directly influenced the constitutions of dozens of other nations, from Latin America to post-WWII Japan and Germany." },
  { tag: "Longevity", text: "It remains the oldest single-document written national constitution still in active use anywhere in the world today." },
  { tag: "Convention", text: "The Constitutional Convention was originally authorized only to revise the Articles of Confederation — delegates scrapped that mandate and wrote an entirely new framework instead." },
  { tag: "Convention", text: "Delegates met in near-total secrecy through the summer of 1787, keeping windows shut against the heat and posting guards to keep the debates from leaking out." },
  { tag: "Convention", text: "The Convention gained urgency after Shays' Rebellion, an armed uprising of indebted Massachusetts farmers that exposed how weak the Articles of Confederation truly were." },
  { tag: "Framers", text: "Alexander Hamilton was the only New York delegate to sign the Constitution — his two fellow delegates had already walked out of the Convention." },
  { tag: "Compromises", text: "The Great Compromise (or Connecticut Compromise) resolved the small-state/large-state standoff by pairing a population-based House with a Senate of equal representation." },
  { tag: "Compromises", text: "The Virginia Plan favored a strong national government with representation by population, while the New Jersey Plan favored equal representation for every state — the Great Compromise blended the two." },
  { tag: "Convention", text: "Three delegates who stayed until the Constitution was finished still refused to sign it: Edmund Randolph, George Mason, and Elbridge Gerry." },
  { tag: "Framers", text: "Elbridge Gerry, who refused to sign the Constitution over its missing bill of rights, later lent his name to the term \"gerrymander\" as governor of Massachusetts." },
  { tag: "Federalist Papers", text: "The Federalist Papers, 85 essays urging ratification, were written under the shared pseudonym \"Publius\" by Alexander Hamilton, James Madison, and John Jay." },
  { tag: "Federalist Papers", text: "Federalist No. 10, written by Madison, argued that a large republic was actually better suited than a small one to controlling the dangers of political factions." },
  { tag: "Ratification", text: "Delaware was the first state to ratify the Constitution, on December 7, 1787 — the origin of its nickname, \"The First State.\"" },
  { tag: "Anti-Federalists", text: "Opponents of ratification, known as Anti-Federalists, worried the new federal government would grow too powerful — their pressure is largely why the Bill of Rights exists at all." },
  { tag: "Trivia", text: "The entire Constitution, including all the signatures, is only about 4,543 words long — shorter than many magazine feature articles." },
  { tag: "Trivia", text: "The Constitution was handwritten on four sheets of parchment by Jacob Shallus, a Pennsylvania State Assembly clerk reportedly paid about $30 for the job." },
  { tag: "Article I", text: "Article I, Section 8 lists Congress's enumerated powers — including coining money, declaring war, and running post offices — and ends with the sweeping \"Necessary and Proper Clause.\"" },
  { tag: "Article I", text: "The Constitution bans both bills of attainder (punishing someone without a trial) and ex post facto laws (criminalizing acts that were legal when committed)." },
  { tag: "Article I", text: "Revenue-raising bills must originate in the House of Representatives under the Constitution's Origination Clause, reflecting the House's closer tie to voters." },
  { tag: "Article I", text: "Congress is constitutionally required to keep and publish a journal of its proceedings, though it can vote to keep certain parts secret." },
  { tag: "Article II", text: "The Constitution requires presidents to be at least 35 years old, a natural-born U.S. citizen, and a resident of the country for at least 14 years." },
  { tag: "Article II", text: "Article II requires the president to periodically report to Congress on the \"State of the Union\" — a duty that evolved into today's televised annual address." },
  { tag: "Article II", text: "The Constitution gives the president broad power to grant pardons and reprieves for federal offenses — except, notably, in cases of impeachment." },
  { tag: "Article II", text: "Treaties negotiated by the president only take effect with the advice and consent of two-thirds of the Senate." },
  { tag: "Article III", text: "Treason is the only crime explicitly defined in the Constitution itself, requiring either an overt act witnessed by two people or a confession in open court." },
  { tag: "Article III", text: "The Supreme Court holds both original jurisdiction, hearing certain cases directly, and appellate jurisdiction, reviewing rulings from lower courts." },
  { tag: "Article IV", text: "The Full Faith and Credit Clause in Article IV requires every state to honor the public acts, records, and court judgments of other states." },
  { tag: "Article IV", text: "Article IV guarantees every state a \"Republican Form of Government,\" though courts have long treated that guarantee as a political question rather than one for judges to enforce." },
  { tag: "Article IV", text: "New states are admitted to the Union under Article IV, but no state can be carved out of an existing one without that state's own consent." },
  { tag: "Article VI", text: "Article VI bars any religious test as a qualification for holding federal office — a direct rejection of practices common across Europe at the time." },
  { tag: "Article VII", text: "The Constitution only needed ratifying conventions in 9 of the 13 states to take effect — the framers deliberately bypassed state legislatures, which they saw as too tied to local interests." },
  { tag: "Second Amendment", text: "The Second Amendment ties a \"well regulated Militia\" to the right to keep and bear arms, phrasing that has fueled centuries of legal debate over its scope." },
  { tag: "Third Amendment", text: "The Third Amendment, barring the government from quartering soldiers in private homes without consent, is the least litigated provision in the entire Constitution." },
  { tag: "Fifth Amendment", text: "The Fifth Amendment's Double Jeopardy Clause bars a government from prosecuting someone twice for the same offense — though under the \"separate sovereigns\" doctrine, state and federal governments can each still prosecute once." },
  { tag: "Fifth Amendment", text: "The Fifth Amendment's Takings Clause requires the government to pay \"just compensation\" whenever it seizes private property for public use." },
  { tag: "Sixth Amendment", text: "The Sixth Amendment guarantees the right to confront witnesses and to a speedy, public trial — and, as later interpreted, to a lawyer even if the defendant can't afford one." },
  { tag: "Seventh Amendment", text: "The Seventh Amendment preserves the right to a jury trial in federal civil cases, but only when the amount in controversy exceeds twenty dollars — a figure never adjusted for inflation." },
  { tag: "Eighth Amendment", text: "The Eighth Amendment bans excessive bail, excessive fines, and \"cruel and unusual punishments,\" language borrowed almost verbatim from England's 1689 Bill of Rights." },
  { tag: "Ninth Amendment", text: "The Ninth Amendment clarifies that listing certain rights in the Constitution doesn't mean the people don't retain other rights left unspoken." },
  { tag: "Tenth Amendment", text: "The Tenth Amendment reserves any powers not given to the federal government, and not denied to the states, to the states or to the people." },
  { tag: "Eleventh Amendment", text: "The Eleventh Amendment (1795) was the first amendment adopted after the Bill of Rights, limiting individuals' ability to sue states in federal court." },
  { tag: "Twelfth Amendment", text: "The Twelfth Amendment (1804) requires separate ballots for president and vice president, fixing a flaw exposed by the chaotic tied election of 1800." },
  { tag: "Sixteenth Amendment", text: "The Sixteenth Amendment (1913) authorized a federal income tax, overriding an 1895 Supreme Court ruling that had struck one down as unconstitutional." },
  { tag: "Seventeenth Amendment", text: "Before the Seventeenth Amendment (1913), U.S. Senators were chosen by state legislatures rather than elected directly by voters." },
  { tag: "Twentieth Amendment", text: "The Twentieth Amendment (1933) moved Inauguration Day from March 4 to January 20, shortening the awkward \"lame duck\" gap between election and taking office." },
  { tag: "Twenty-Third Amendment", text: "The Twenty-Third Amendment (1961) gave residents of Washington, D.C. the right to vote in presidential elections, despite the district having no voting members of Congress." },
  { tag: "Twenty-Fourth Amendment", text: "The Twenty-Fourth Amendment (1964) outlawed poll taxes in federal elections, removing a tool historically used to disenfranchise Black voters." },
  { tag: "Unratified", text: "The Equal Rights Amendment passed Congress in 1972, and a 38th state ratified it in 2020 — but an expired congressional deadline and unresolved legal disputes mean it still hasn't been certified as part of the Constitution." },
  { tag: "Numbers", text: "Of the 12 amendments the First Congress sent to the states in 1789, 10 were ratified right away as the Bill of Rights, one became the 27th Amendment in 1992, and one — reapportioning House seats — has still never been ratified." },
  { tag: "Numbers", text: "Congress has proposed roughly 11,000 constitutional amendments across U.S. history — only 27 have ever been ratified." },
  { tag: "Numbers", text: "The 26th Amendment, lowering the voting age to 18, was ratified faster than any other in history — in about 100 days during 1971." },
  { tag: "Landmark Cases", text: "In McCulloch v. Maryland (1819), the Supreme Court upheld Congress's implied powers under the Necessary and Proper Clause and ruled that states can't tax federal institutions." },
  { tag: "Landmark Cases", text: "Gibbons v. Ogden (1824) gave Congress broad authority to regulate interstate commerce, a ruling that still underpins much of federal regulatory power today." },
  { tag: "Landmark Cases", text: "Dred Scott v. Sandford (1857), later overturned by the 13th and 14th Amendments, wrongly held that Black Americans could never be citizens under the Constitution." },
  { tag: "Landmark Cases", text: "Plessy v. Ferguson (1896) upheld \"separate but equal\" racial segregation, a doctrine the Court unanimously rejected 58 years later in Brown v. Board of Education." },
  { tag: "Landmark Cases", text: "Brown v. Board of Education (1954) ruled that segregated public schools violated the Fourteenth Amendment's Equal Protection Clause." },
  { tag: "Landmark Cases", text: "Miranda v. Arizona (1966) is why police must inform suspects of their Fifth and Sixth Amendment rights before questioning — the origin of the \"Miranda warning.\"" },
  { tag: "Landmark Cases", text: "United States v. Nixon (1974) forced President Nixon to turn over the Watergate tapes, establishing that executive privilege isn't absolute." },
  { tag: "Landmark Cases", text: "Korematsu v. United States (1944), which upheld the internment of Japanese Americans during WWII, was formally repudiated by the Supreme Court itself in 2018." },
  { tag: "Landmark Cases", text: "Obergefell v. Hodges (2015) held that the Fourteenth Amendment guarantees same-sex couples the right to marry nationwide." }
];
